name: 'makeopendata'
version: '1.0.0'
config-version: 2

profile: 'makeopendata'

model-paths: ["1_data"]
analysis-paths: ["2_analyses"]
test-paths: ["3_tests"]
seed-paths: ["4_seeds"]
macro-paths: ["5_macros"]
snapshot-paths: ["6_snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models: