# This file contains the list of sources to be used by the application

codes_postaux :
  url :  https://datanova.laposte.fr/data-fair/api/v1/datasets/laposte-hexasmal/metadata-attachments/base-officielle-codes-postaux.csv
  source : https://www.data.gouv.fr/fr/datasets/base-officielle-des-codes-postaux/#/resources

codes_geographiques_communes :
  url: https://www.data.gouv.fr/fr/datasets/r/8262de72-138f-4596-ad2f-10079e5f4d7c
  source : https://www.data.gouv.fr/fr/datasets/code-officiel-geographique-cog/

codes_geographiques_communes_TOM : 
  url: https://www.data.gouv.fr/fr/datasets/r/09f50ab9-f5b6-400a-b599-643e283d7268
  source : https://www.data.gouv.fr/fr/datasets/code-officiel-geographique-cog/

codes_geographiques_arrondissements : 
  url: https://www.data.gouv.fr/fr/datasets/r/21fdff26-33a9-4b8e-bfd9-ce6d2ed5659e
  source : https://www.data.gouv.fr/fr/datasets/code-officiel-geographique-cog/

codes_geographiques_departements: 
  url: https://www.data.gouv.fr/fr/datasets/r/e436f772-b05d-47f8-b246-265faab8679f
  source : https://www.data.gouv.fr/fr/datasets/code-officiel-geographique-cog/

codes_geographiques_regions : 
  url: https://www.data.gouv.fr/fr/datasets/r/53cb77ce-8a93-4924-9d5d-920bbe7c679f
  source : https://www.data.gouv.fr/fr/datasets/code-officiel-geographique-cog/

dvf_2023:
  url: https://files.data.gouv.fr/geo-dvf/latest/csv/2023/full.csv.gz
  source: https://www.data.gouv.fr/fr/datasets/demandes-de-valeurs-foncieres-geolocalisees/

logement_2020:
  url: https://www.insee.fr/fr/statistiques/fichier/7705908/RP2020_LOGEMT_csv.zip
  source : https://www.insee.fr/fr/statistiques/7705908?sommaire=7637890