# This file contains the list of sources to be used by the application


sirene_06_2024:
  source_url: https://files.data.gouv.fr/insee-sirene/StockEtablissement_utf8.zip
  source_reference : https://www.insee.fr/fr/information/3591226
  source_csv_delimiter : ','
  source_db_schema : "sources"