# This file contains the list of sources to be used by the application

cog_poste :
  source_url :  https://datanova.laposte.fr/data-fair/api/v1/datasets/laposte-hexasmal/metadata-attachments/base-officielle-codes-postaux.csv
  source_reference : https://www.data.gouv.fr/fr/datasets/base-officielle-des-codes-postaux/#/resources
  source_csv_delimiter : ','
  source_db_schema : "sources"

cog_communes :
  source_url: https://unpkg.com/@etalab/decoupage-administratif@4.0.0/data/communes.json
  source_reference : https://github.com/datagouv/decoupage-administratif
  source_csv_delimiter : ','
  source_db_schema : "sources"


cog_arrondissements : 
  source_url: https://unpkg.com/@etalab/decoupage-administratif@4.0.0/data/arrondissements.json
  source_reference : https://github.com/datagouv/decoupage-administratif
  source_csv_delimiter : ','
  source_db_schema : "sources"


cog_departements: 
  source_url: https://unpkg.com/@etalab/decoupage-administratif@4.0.0/data/departements.json
  source_reference : https://github.com/datagouv/decoupage-administratif
  source_csv_delimiter : ','
  source_db_schema : "sources"

cog_regions : 
  source_url: https://unpkg.com/@etalab/decoupage-administratif@4.0.0/data/regions.json
  source_reference : https://github.com/datagouv/decoupage-administratif
  source_csv_delimiter : ','
  source_db_schema : "sources"

