version: 2

sources:
  - name: meta
    description: "Metadata tables"
    tables:
      - name: logement_2020_variables
        description: "Dictionnaire des variables pour la table logement_2020. Producteur des données: INSEE. Origine: https://www.data.gouv.fr/fr/datasets/recensement-de-la-population-fichiers-detail-logements-ordinaires-en-2020-1/"
        columns:
          - name: COD_VAR
            description: "Nom de la variable"
            data_type: string
          - name: LIB_VAR
            description: "Libellé de la variable"
            data_type: string
          - name: COD_MOD
            description: "Nom de le modalité"
            data_type: string
          - name: LIB_MOD
            description: "Libellé de la modalité"
            data_type: string
          - name: TYPE_VAR
            description: "Type de la variable (pas applicable en import CSV car tout en text)"
            data_type: string
          - name: LONG_VAR
            description: "Longueur de la variable (pas applicable en import CSV car tout en text)"
            data_type: string