name: Integration Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - staging

jobs:
  dbt:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:12-3.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: make_open_data
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Create Python virtual environment
      run: python3 -m venv dbt-env

    - name: Activate virtual environment and install dependencies
      run: |
        source dbt-env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install s3cmd
      run: |
        source dbt-env/bin/activate
        sudo apt-get update
        sudo apt-get install -y s3cmd

    - name: Set environment variables
      run: |
        echo "POSTGRES_DB=make_open_data" >> $GITHUB_ENV
        echo "POSTGRES_HOST=localhost" >> $GITHUB_ENV
        echo "POSTGRES_PASSWORD=postgres" >> $GITHUB_ENV
        echo "POSTGRES_PORT=5432" >> $GITHUB_ENV
        echo "POSTGRES_USER=postgres" >> $GITHUB_ENV

    - name: Set DBT_PROFILES_DIR
      run: echo "DBT_PROFILES_DIR=." >> $GITHUB_ENV

    - name: check dbt project
      run: |
        source dbt-env/bin/activate
        dbt debug
        
    - name: Extract data and upload it to DB
      run: |
        source dbt-env/bin/activate
        python -m extract
    
    - name: Run dbt seed
      run: |
        source dbt-env/bin/activate
        dbt seed

    - name: Run dbt run
      run: |
        source dbt-env/bin/activate
        dbt run

    - name: Run dbt test
      run: |
        source dbt-env/bin/activate
        dbt test